fix recursion limit
In the CIO (https://github.com/oxidecomputer/cio) repo, I use
`128-column-tables` and the problem is then when I import this
repo, I get the following error:

```
error: recursion limit reached while expanding `impl_valid_grouping_for_tuple_of_columns!`
   --> /Users/macinatormax/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/ce77c38/diesel/src/type_impls/tuples.rs:478:9
    |
478 | /         impl_valid_grouping_for_tuple_of_columns! {
479 | |             @build
480 | |             start_ts = [$($ST,)*],
481 | |             ts = [$($T,)*],
...   |
488 | |             ],
489 | |         }
    | |_________^
...
561 |   __diesel_for_each_tuple!(tuple_impls);
    |   ------------------------------------- in this macro invocation
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`diesel`)
    = note: this error originates in the macro `impl_valid_grouping_for_tuple_of_columns` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I think there was a bug in the sha you were using since it doesn't
happen on the latest sha from their main branch.

Signed-off-by: Jess Frazelle <github@jessfraz.com>